### ISSUE TITLE
Kunde logget ind og ændre kodeord

### ISSUE THREAD

**Issue by mrPrimeBeef** [mrPrimeBeef/FogCarport#30]
http://jcoder.dk:7071/opdaterkundeinfo;jsessionid=node01dx2q4lobj54z1x4l8daolfdjl2.node0

**Comment by pbollhorn** [comment]
Problem should be fixed now:
AccountController.login() now redirects to endpoints "saelgeralleordrer" and "kundeside", instead of calling methods which renders "saelgeralleordrer.html" and "kundeside.html".
The redirect causes the browser to "load a fresh page" and this causes the JSESSIONID cookie to function properly.
